# Generated by Django 4.2.7 on 2025-04-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgenode",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "入门"),
                    (2, "基础"),
                    (3, "进阶"),
                    (4, "高级"),
                    (5, "专家"),
                ],
                default=1,
            ),
        ),
    ]
