# Generated by Django 4.2.7 on 2025-04-07 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_knowledgenode_difficulty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="analysis",
        ),
        migrations.AddField(
            model_name="question",
            name="answer_analysis",
            field=models.TextField(blank=True, verbose_name="答案解析"),
        ),
        migrations.AddField(
            model_name="question",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(
                blank=True, help_text="用于选择题的选项", null=True, verbose_name="选项"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "单选题"),
                    ("multiple_choice", "多选题"),
                    ("fill_blank", "填空题"),
                    ("calculation", "计算题"),
                    ("proof", "证明题"),
                    ("application", "应用题"),
                ],
                default="calculation",
                max_length=20,
                verbose_name="题目类型",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="review_comment",
            field=models.TextField(blank=True, verbose_name="审核意见"),
        ),
        migrations.AddField(
            model_name="question",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
        ),
        migrations.AddField(
            model_name="question",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核者",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="solution_steps",
            field=models.TextField(blank=True, verbose_name="解题步骤"),
        ),
        migrations.AddField(
            model_name="question",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "手动录入"),
                    ("ocr", "OCR识别"),
                    ("import", "批量导入"),
                    ("ai", "AI生成"),
                    ("api", "第三方API"),
                ],
                default="manual",
                max_length=20,
                verbose_name="来源",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                ],
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="用逗号分隔的标签",
                max_length=200,
                verbose_name="标签",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="tips",
            field=models.TextField(blank=True, verbose_name="提示"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.TextField(verbose_name="标准答案"),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=models.TextField(verbose_name="题目内容"),
        ),
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(
                choices=[(1, "简单"), (2, "中等"), (3, "困难")],
                default=1,
                verbose_name="难度等级",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="knowledge_nodes",
            field=models.ManyToManyField(
                related_name="questions",
                to="core.knowledgenode",
                verbose_name="相关知识点",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(max_length=200, verbose_name="题目标题"),
        ),
        migrations.AlterField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
